### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by hcilabustutt** [meschup/project-inf#1]
# Project INF:  Exploration of Multi-Modal Interaction with Smart Home Environments

Official start of this project INF: **20.11.2015**
Official start of this project INF: **20.05.2016**

**Team members:**
* Emine Turan (ET)
* Tobias Schneider (TS)
* Turhan Aral (TA)
* Safak Mumin (SM)

### Milestone 1 (20.12.2015)
- [ ] Meschup platforms runs on all RPIs
- [ ] z-ways-server installed on RPIs with Z-Wave adapter
- [ ] Zwave Switch installed and functional in Z-Wave server
- [ ] Zwave Dimmer installed and functional in Z-Wave server
- [ ] Zwave Danalock installed and functional in Z-Wave server
- [ ] Zwave Dimmer can be controlled via z-ways-server API (http://192.168.7.1:8083)
- [ ] Edimax SmartPlugs can be discovered via nodeJS
- [ ] Edimax SmartPlugs can be controlled via nodeJS
- [ ] Edimax SmartPlugMeter monitored via nodeJS

### Milestone 2 (20.01.2016)
- [ ] All Zwave devices can be monitored and controlled via nodeJS (by using the z-ways-server APIs)
- [ ] Edimax SmartPlugs fully integrated as meSchup modules
- [ ] Implement use case I. as a meschup rule: Lighting of lamps in a room are controlled by daytime (off during day, optionally on when dark enough) and presence of people (using BLE beacons). This means, when persons are close and its dark enough the lighting turns on, otherwise when no people are present the lighting turns off. 
- [ ] ...
